version: '3.1'
services:
  shib-proxy2:
    image: uscdev/shib-proxy
    environment:
      - CLIENT_APP_SCHEME=https
      - CLIENT_APP_HOSTNAME=localhost
      - NGINX_PROXY_DESTINATION=http://my-app:4200
      - CLIENT_APP_SECURE_PATH=/
    ports:
      - 80:80
      - 443:443
   #     - 8984:80
   #     - 8983:443
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.port=443
        - com.df.serviceDomain=my-app.docker.usc.edu
        - com.df.sslVerifyNone=true
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  my-app:
    image: uscdev/my-app
    networks:
      - proxy
    ports:
      - 8985:4200
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  proxy:
    external:
      name: proxy
